name: Matthew T Mackenzie
favicon: null
layout_spectrum: 0.9563649352639914
typography_spectrum: 0.28148942766711116
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.32735643489286304
  lightness: 0.14028248842805624
  saturation: 0.23114300682209432
  rhythmicContrast: 0.49526976817287505
purpose: []
